version: '2'
services:
  nginx:
    restart: always
    hostname: nginx
    build: ./nginx/
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/config/ssl:/etc/nginx/ssl
      - /etc/localtime:/etc/localtime:ro
      - ./letsencrypt/conf:/etc/letsencrypt
      - ./letsencrypt/html:/tmp/letsencrypt
    environment:
      - LE_RENEW_HOOK=docker kill -s HUP @CONTAINER_NAME@

  letsencrypt:
    restart: always
    image: kvaps/letsencrypt-webroot
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt/conf:/etc/letsencrypt
      - ./letsencrypt/html:/tmp/letsencrypt
    depends_on:
      - nginx
    links:
      - nginx
    environment:
      - DOMAINS=ocrbybat.lespot-bouygues.com
      - EMAIL=bonjour@bouygues.com
      - WEBROOT_PATH=/tmp/letsencrypt
      - EXP_LIMIT=30
      - CHECK_FREQ=30

  webapp:
    restart: always
    hostname: webapp
    build: ./Bouygues-Const-WebApp/
    ports:
      - "80"
    volumes:
      - ./Bouygues-Const-WebApp/dist:/usr/local/apache2/htdocs/

  apiserver:
    restart: always
    hostname: apiserver
    build: ./Bouygues-Const/
    ports:
      - "8080:3000"
    depends_on:
      - mongodb
    links:
      - mongodb
      - openocr
    volumes:
      - ./Bouygues-Const/:/app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /volumes/docker/mongodb:/var/lib/mongodb
      - /volumes/docker/mongodb-data:/data/db
      - ./mongodb/config/mongod.conf:/etc/mongod.conf
      - ./log/mongodb/mongodb.log:/var/log/mongodb/mongod.log
    ports:
      - "27017:27017"
    restart: always

  adminmongo:
    build: ./mongodb/gui/
    container_name: adminmongo
    links:
      - mongodb
    ports:
      - "3000"
    restart: always

  # Start messaging broker
  rabbitmq:
    image: tutum/rabbitmq
    dns: ["8.8.8.8"]
    environment:
      - "RABBITMQ_PASS=Phaish9ohbaidei6oole"

  # Start transformation worker
  strokewidthtransform:
    image: tleyden5iwx/open-ocr-preprocessor
    volumes:
      - ./scripts/:/opt/open-ocr/
    dns: ["8.8.8.8"]
    links:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -preprocessor stroke-width-transform"

  # Start OCR worker
  openocrworker:
    image: tleyden5iwx/open-ocr
    volumes:
      - ./scripts/:/opt/open-ocr/
    dns: ["8.8.8.8"]
    links:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/"

  # Start http server
  openocr:
    image: tleyden5iwx/open-ocr
    dns: ["8.8.8.8"]
    volumes:
      - ./scripts/:/opt/open-ocr/
    links:
      - rabbitmq
    ports:
      - "9292:9292"
    command: "/opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292"
